config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/dashboard', to: 'users#show', as: 'dashboard'
  get 'thanks', to: 'charges#new', as: 'thanks'
  get '/backing/:id', to: 'ebooks#backing', as: 'ebooks_backing'
  post '/backing/charge/', to: 'charges#ebook_backing_stripe', as: 'ebook_backing_stripe'
  get '/auth/twitter/callback', to: 'sessions#oauth_login'
  resource :cart
  resources :charges, only: [:create]
  resources :ebooks, only: [:index, :show, :new, :create]
  resources :orders, only: [:index]
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :show]
  namespace :users do
    resources :authors, only: [:index, :create, :show]
    resources :ebooks, only: [:show]
    namespace :authors do
      resources :ebooks, only: [:new, :create, :show, :edit, :update]
    end
  end
  namespace :admin do
    get "/dashboard", to: "users#show", as: "dashboard"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_many :user_ebooks
  has_many :ebooks, through: :user_ebooks
  has_many :authors

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :role, presence: true

  enum role: ["user", "admin"]

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info['uid']
      new_user.email              = auth_info['extra']['raw_info']['screen_name']
      new_user.password           = auth_info['credentials']['token']
      new_user.token              = auth_info['credentials']['token']
      new_user.secret             = auth_info['credentials']['secret']
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  
end

app/controllers/users/authors/ebooks_controller.rb
class Users::Authors::EbooksController < ApplicationController
  def show
    @ebook = Ebook.find(params[:id])
    @category_names = parse_categories(@ebook.categories)
  end

  def new
    @author = Author.find(params[:author])
    @ebook = Ebook.new(author: @author)
  end

  def create
    ebook = Ebook.new(title: params['title'],
                      description: params['description'],
                      body: params['body'],
                      price: params['price'],
                      author_id: params['author_id'])
    if ebook.save
      flash[:success] = "eBook created"
      redirect_to users_authors_ebook_path(ebook)
    else
      flash[:failure] = "eBook was not created"
      redirect_to users_authors_path
    end
  end

  def edit
    @ebook = Ebook.find(params[:id])
    @categories = Category.all
  end

  def update
    @ebook = Ebook.find(params[:id])
    categories = Category.where(name: params[:categories])
    @ebook.categories << categories

    redirect_to users_authors_ebook_path(@ebook)
  end

  private

    def parse_categories(categories)
      names = []
      categories.each do |category|
        names << category.name
      end
      names
    end
end

app/controllers/users/authors_controller.rb
class Users::AuthorsController < ApplicationController
  def index
    @authors = Author.where(user_id: current_user.id)
  end

  def create
    user = User.find(current_user.id)
    author = Author.new(name: params['name'], user: user)
    if author.save
      user.authors << author
      flash[:success] = "Author created"
      redirect_to users_authors_path
    else
      flash[:failure] = "Author was not created"
      redirect_to users_authors_path
    end
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/users/ebooks_controller.rb
class Users::EbooksController < ApplicationController
  def show
    @ebook = current_user.ebooks.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Logged in with #{@user.email}"
      redirect_to dashboard_path
    else
      flash[:message] = "Account creation has failed."
      redirect_to new_user_path
    end
  end

  def show
    if !current_user.nil?
      @user = current_user
      @ebooks = current_user.ebooks
    else
      not_found
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :street_address, :city, :zip_code)
    end

end

app/views/users/new.html.erb
<div class="create-form">
  <%= form_tag(@user) do %>
    <div class="form-group">
      <%= label_tag :email %>
      <%= text_field_tag 'user[email]' %>
    </div>
    <div class="form-group">
      <%= label_tag :password %>
      <%= password_field_tag 'user[password]' %>
    </div>
    <div class="form-group">
      <%= label_tag :password_confirmation, 'Confirm Password' %>
      <%= password_field_tag 'user[password_confirmation]' %>
    </div>
    <div class="form-group">
      <%= label_tag :first_name %>
      <%= text_field_tag 'user[first_name]' %>
    </div>
    <div class="form-group">
      <%= label_tag :last_name %>
      <%= text_field_tag 'user[last_name]' %>
    </div>
    <div class="form-group">
      <%= label_tag :street_address %>
      <%= text_field_tag 'user[street_address]' %>
    </div>
    <div class="form-group">
      <%= label_tag :city %>
      <%= text_field_tag 'user[city]' %>
    </div>
    <div class="form-group">
      <%= label_tag :zip_code %>
      <%= text_field_tag 'user[zip_code]' %>
    </div>
      <%= submit_tag 'Submit', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>Welcome back, <%= @user.email %>.</h2>
<br /><hr />
<h4>Purchased eBooks</h4>
<p>Click on an eBook to see more information.</p>
<br>
<% @ebooks.each do |ebook| %>
  <div class="ebook">
    <%= link_to ebook.title, users_ebook_path(ebook) %>
  </div>
<% end %>