config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/dashboard', to: 'users#show', as: 'dashboard'
  get 'thanks', to: 'charges#new', as: 'thanks'
  get '/backing/:id', to: 'ebooks#backing', as: 'ebooks_backing'
  post '/backing/charge/', to: 'charges#ebook_backing_stripe', as: 'ebook_backing_stripe'
  get '/auth/twitter/callback', to: 'sessions#oauth_login'
  resource :cart
  resources :charges, only: [:create]
  resources :ebooks, only: [:index, :show, :new, :create]
  resources :orders, only: [:index]
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :show]
  namespace :users do
    resources :authors, only: [:index, :create, :show]
    resources :ebooks, only: [:show]
    namespace :authors do
      resources :ebooks, only: [:new, :create, :show, :edit, :update]
    end
  end
  namespace :admin do
    get "/dashboard", to: "users#show", as: "dashboard"
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def total_count
    contents.values.sum
  end

  def order_hash
    ebooks = {}
    contents.each do |ebook_id, quantity|
      ebooks[Ebook.find(ebook_id)] = quantity
    end
    ebooks
  end

  def destroy
    @contents.clear
  end

  def cart_total
    total = 0
    contents.each do |ebook_id, quantity|
      ebooks_cost = Ebook.find(ebook_id).price * quantity
      total += ebooks_cost
    end
    total
  end

  def cart_total_stripe
    cart_total.to_s.tr('.', '0')
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    id = params[:ebook_id].to_s
    ebook = Ebook.find_by(id: id)
    @cart.add_item(ebook.id)
    session[:cart] = @cart.contents
    redirect_back(fallback_location: root_path)
    flash[:success] = "#{ebook.title} added to cart"
  end

  def show
    @cart = Cart.new(session[:cart])
    @ebooks = Ebook.find(@cart.contents.keys)
  end

  def destroy
    ebook = Ebook.find(params[:format])
    @cart.contents.delete(params[:format])
    flash[:success] = "Removed <a href=#{ebook_path(ebook)}>#{ebook.title}</a> from your cart."

    redirect_to cart_path
  end
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>
<br /><hr /><br />
<table class="table cart-table">
<% @ebooks.each do |ebook| %>
  <tr class="cart-item">
    <td><%= ebook.title %></td>
    <td><%= number_to_currency(ebook.price) %></td>
    <td><%= button_to "X", cart_path(ebook), method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
  <tr>
    <td></td>
    <td></td>
    <td>
      <% if current_user %>
      <%= form_tag charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="amount">
            <span>Total Cost: <%= number_to_currency(@cart.cart_total) %></span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-name="Bookfund"
                data-description="Secure Payment Platform"
                data-amount="<%= @cart.cart_total_stripe %>"
                data-locale="auto"></script>
        <% end %>
      <% else %>
        <%= link_to "Login or Register to checkout", login_path %>
      <% end %>
    </td>
  </tr>
</table>