config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/dashboard', to: 'users#show', as: 'dashboard'
  get 'thanks', to: 'charges#new', as: 'thanks'
  get '/backing/:id', to: 'ebooks#backing', as: 'ebooks_backing'
  post '/backing/charge/', to: 'charges#ebook_backing_stripe', as: 'ebook_backing_stripe'
  get '/auth/twitter/callback', to: 'sessions#oauth_login'
  resource :cart
  resources :charges, only: [:create]
  resources :ebooks, only: [:index, :show, :new, :create]
  resources :orders, only: [:index]
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :show]
  namespace :users do
    resources :authors, only: [:index, :create, :show]
    resources :ebooks, only: [:show]
    namespace :authors do
      resources :ebooks, only: [:new, :create, :show, :edit, :update]
    end
  end
  namespace :admin do
    get "/dashboard", to: "users#show", as: "dashboard"
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ebook_categories
  has_many :ebooks, through: :ebook_categories

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params['id'])
  end
end

app/views/categories/index.html.erb
<div class="categories">
  <h1>Browse Categories</h1>
<table class="table category-table">
<% @categories.each_slice(4) do |slice| %>
  <tr>
  <% slice.each do |category| %>
    <td class="category">
      <%= link_to "#{category.name}", category_path(category), class: 'category-name' %>
    </td>
  <% end %>
  </tr>
<% end %>
</table>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %> eBooks</h1>

<% @category.ebooks.each_slice(4) do |slice| %>
<div class="row">
  <div class="col">&nbsp;</div>
  <% slice.each do |ebook| -%>
  <div class="ebook-index-item col-lg-2">
      <div class="title">
        <h5><%= link_to "#{ebook.title}", ebook_path(ebook) %></h5>
      </div>
      <div class="description">
        <%= ebook.short_description %>
      </div>
      <% if current_user && current_user.ebooks.exists?(ebook.id) %>
        <p class="index-add-cart btn btn-primary">Already Owned</p>
      <% else %>
        <%= button_to "Add to Cart", cart_path(ebook_id: ebook.id), class: 'index-add-cart btn btn-primary' %>
      <% end %>
    </div>
    <% end -%>
    <div class="col">&nbsp;</div>
  </div>
<% end %>