config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#show'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/dashboard', to: 'users#show', as: 'dashboard'
  get 'thanks', to: 'charges#new', as: 'thanks'
  get '/backing/:id', to: 'ebooks#backing', as: 'ebooks_backing'
  post '/backing/charge/', to: 'charges#ebook_backing_stripe', as: 'ebook_backing_stripe'
  get '/auth/twitter/callback', to: 'sessions#oauth_login'
  resource :cart
  resources :charges, only: [:create]
  resources :ebooks, only: [:index, :show, :new, :create]
  resources :orders, only: [:index]
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :show]
  namespace :users do
    resources :authors, only: [:index, :create, :show]
    resources :ebooks, only: [:show]
    namespace :authors do
      resources :ebooks, only: [:new, :create, :show, :edit, :update]
    end
  end
  namespace :admin do
    get "/dashboard", to: "users#show", as: "dashboard"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :not_found
  helper_method :current_cart
  helper_method :current_admin?
  helper_method :require_admin
  before_action :set_cart

  def current_user
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end

  def not_found
    raise ActionController::RoutingError.new('404 - The page you are looking for does not exist')
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to 'Bookfund', root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'eBooks', ebooks_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      <% if current_user && current_user.admin? %>
      <li class="nav-item">
        <%= link_to 'Admin Dashboard', admin_dashboard_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Cart: #{@cart.total_count}", cart_path, class: 'nav-link' %>
      </li>
      <% if current_user %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
            <%= link_to 'My Authors', users_authors_path, class: 'nav-link' %>
            <%= link_to 'Post eBook', users_authors_path, class: 'nav-link' %>
            <%= link_to 'Past Orders', orders_path, class: 'nav-link' %>
            <%= link_to 'Logout', logout_path, class: 'nav-link' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>